### ISSUE TITLE
fails to load

### ISSUE THREAD

**Issue by martinschorb** [platybrowser/mmb-python#2]
@tischer, @tischi

```
java.lang.UnsupportedOperationException: No image data found in: https://git.embl.de/pape/covid-em/-/raw/master/data/Covid19-S4-Area2/images/remote
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.addSourcesFromJson(PlatyBrowserImageSourcesModel.java:112)
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.addSources(PlatyBrowserImageSourcesModel.java:77)
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.<init>(PlatyBrowserImageSourcesModel.java:53)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.<init>(PlatyBrowserSourcesPanel.java:66)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowser.<init>(PlatyBrowser.java:32)
	at de.embl.cba.platynereis.platybrowser.command.PlatyBrowserOpenAdvancedCommand.run(PlatyBrowserOpenAdvancedCommand.java:26)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.UnsupportedOperationException
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.addSources(PlatyBrowserImageSourcesModel.java:82)
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.<init>(PlatyBrowserImageSourcesModel.java:53)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.<init>(PlatyBrowserSourcesPanel.java:66)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowser.<init>(PlatyBrowser.java:32)
	at de.embl.cba.platynereis.platybrowser.command.PlatyBrowserOpenAdvancedCommand.run(PlatyBrowserOpenAdvancedCommand.java:26)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.UnsupportedOperationException: No image data found in: https://git.embl.de/pape/covid-em/-/raw/master/data/Covid19-S4-Area2/images/remote
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.addSourcesFromJson(PlatyBrowserImageSourcesModel.java:112)
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.addSources(PlatyBrowserImageSourcesModel.java:77)
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.<init>(PlatyBrowserImageSourcesModel.java:53)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.<init>(PlatyBrowserSourcesPanel.java:66)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowser.<init>(PlatyBrowser.java:32)
	at de.embl.cba.platynereis.platybrowser.command.PlatyBrowserOpenAdvancedCommand.run(PlatyBrowserOpenAdvancedCommand.java:26)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.UnsupportedOperationException
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.addSources(PlatyBrowserImageSourcesModel.java:82)
	at de.embl.cba.platynereis.platysources.PlatyBrowserImageSourcesModel.<init>(PlatyBrowserImageSourcesModel.java:53)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.<init>(PlatyBrowserSourcesPanel.java:66)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowser.<init>(PlatyBrowser.java:32)
	at de.embl.cba.platynereis.platybrowser.command.PlatyBrowserOpenAdvancedCommand.run(PlatyBrowserOpenAdvancedCommand.java:26)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
One caveat:
I am not 100% sure if this `https://git.embl.de/pape/covid-em/-/raw/master/data/Covid19-S4-Area2/images/remote` is the correct way to specify the git repo.
I have only done this on github so far and did the corresponding thing on gitlab, but I think this was never tested.

**Comment by martinschorb** [comment]
The problem is somewhere else. It finds the data version but cannot load it.

When I try to load it locally (from the group share) it bursts into Java Exceptions and completely hangs.

**Comment by martinschorb** [comment]
I managed to copy the exceptions on my mac before it froze with 100% CPU load

:

ooops:
```
You can't comment at this time — your comment is too long (maximum is 65536 characters). 
```

**Comment by martinschorb** [comment]
Here they are:

The stupid log file won't upload...

It's here:
https://git.embl.de/pape/covid-em/-/issues/1

**Comment by constantinpape** [comment]
> The problem is somewhere else. It finds the data version but cannot load it.
> 
> When I try to load it locally (from the group share) it bursts into Java Exceptions and completely hangs.

Ok, I will try this again from the group share, we should first double check this.
I am in a meeting now, will check after that.

**Comment by tischi** [comment]
Hey guys, I don't expect it to work from Fiji yet, because I did no have time to implement the authorisation stuff. Let me know when there is data and I can start testing!

**Comment by constantinpape** [comment]
> Hey guys, I don't expect it to work from Fiji yet, because I did no have time to implement the authorisation stuff. Let me know when there is data and I can start testing and developing the code for this!

The data is there already. I will quickly double check that it works from the EMBL share now and then close details.

**Comment by constantinpape** [comment]
@martinschorb I can load it on the group share:

![Screenshot from 2020-05-15 15-37-31](https://user-images.githubusercontent.com/4263537/82056374-28c45a00-96c2-11ea-96d7-f982cc82024c.png)

![Screenshot from 2020-05-15 15-37-42](https://user-images.githubusercontent.com/4263537/82056392-311c9500-96c2-11ea-9684-64cf7e103ed9.png)

![Screenshot from 2020-05-15 15-37-47](https://user-images.githubusercontent.com/4263537/82056413-3aa5fd00-96c2-11ea-9cbb-2a2b25173253.png)

![Screenshot from 2020-05-15 15-37-56](https://user-images.githubusercontent.com/4263537/82056421-3ed21a80-96c2-11ea-937c-c89260ae040d.png)

**Comment by constantinpape** [comment]
@tischi this is the repository with all the metadata:
https://git.embl.de/pape/covid-em
The data is on s3 already; s3 bucket and path in bucket are in the xmls

**Comment by martinschorb** [comment]
For me it loads as well. BUT: In the last step, where BDV shows the data (it does this for me too) I get the massive exceptions and Java freeze. This happens on Windows(3dcloud VM) as well as on Mac.

**Comment by martinschorb** [comment]
confirm: Linux works

**Comment by constantinpape** [comment]
> For me it loads as well. BUT: In the last step, where BDV shows the data (it does this for me too) I get the massive exceptions and Java freeze. This happens on Windows(3dcloud VM) as well as on Mac.

Ok, weird.
I am using it on linux via x2go and it loads fine for me, no exceptions and I can browse the data.

**Comment by constantinpape** [comment]
@tischi I looked at the exception Martin posted in the other issue:
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:112)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:20)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:451)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:20)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:498)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:475)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:177)
```

This looks like the old issue we had when the empty chunks were not loaded correctly.
@martinschorb are you sure you are using the latest version of MMB?

**Comment by martinschorb** [comment]
I just fetched it from the EMBL-CBA update site, so I guess so...

**Comment by martinschorb** [comment]
When I choose platyprowser instead of Custom data, I get:

```https://raw.githubusercontent.com/platybrowser/platybrowser-backend/master/data/1.0.1/images/remote/sbem-6dpf-1-whole-raw.xml
mpicbg.spim.data.SpimDataInstantiationException: could not find XmlIoBasicImgLoader implementation for format bdv.n5.s3
	at mpicbg.spim.data.generic.sequence.ImgLoaders.createXmlIoForFormat(ImgLoaders.java:72)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:110)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:95)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1356)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:61)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:581)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.showIntensitySource(PlatyBrowserSourcesPanel.java:417)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToViewer(PlatyBrowserSourcesPanel.java:392)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:368)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:333)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowser.<init>(PlatyBrowser.java:46)
	at de.embl.cba.platynereis.platybrowser.command.PlatyBrowserOpenCommand.run(PlatyBrowserOpenCommand.java:24)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:293)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:64)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:581)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.showIntensitySource(PlatyBrowserSourcesPanel.java:417)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToViewer(PlatyBrowserSourcesPanel.java:392)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:368)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:333)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowser.<init>(PlatyBrowser.java:46)
	at de.embl.cba.platynereis.platybrowser.command.PlatyBrowserOpenCommand.run(PlatyBrowserOpenCommand.java:24)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
> I just fetched it from the EMBL-CBA update site, so I guess so...

Ok.
@tischi this could be a problem with the different bdv-core version you are using.
Maybe this is not pulled in correctly for Martin.

**Comment by tischi** [comment]
@martinschorb 

1. you need to download update site and then **do not install anything else** later, because I am relying on a special bdv-version.
2. why does this work? the authentication should not work?!

**Comment by martinschorb** [comment]
> * you need to download update site and then **do not install anything else** later, because I am relying on a special bdv-version.

Hmm, this does not seem to be very user-friendly, especially when we want to use this procedure to make data available for external collaborators. What do your reviewers say to this...? 
If it cannot be avoided, MMB should better be a standalone application and not be part of Fiji, because it contradicts the Fiji idea of having as many plugins as desired/needed.


> * why does this work? the authentication should not work?!

I tried with local data from the group share.

**Comment by constantinpape** [comment]
> Hmm, this does not seem to be very user-friendly, especially when we want to use this procedure to make data available for external collaborators. What do your reviewers say to this...?

We hope that this is a temporary issue and to push these changes upstream eventually.
There are actually fixes for some genuine BDV issues in there, so it should def. go upstream ...

**Comment by tischi** [comment]
> Hmm, this does not seem to be very user-friendly,

True, but sadly the response time to pull requests against bdv-core is so slow that I don't know how to fix this right now.

**Comment by tischi** [comment]
@constantinpape 
The `remote` location was missing in the `images.json` file.
I added it manually.

**Comment by martinschorb** [comment]
OK,

then for now, I have tried with a fresh Fiji installation for MMB only.
- Platybrowser works.
- Our custom data also works (from group share)

Given the load of dependencies that your plugins require, there is always the risk of something to misbehave.

I think we should make sure that at least together with BDV-Playground, there is a peaceful co-existence. ;-)

**Comment by constantinpape** [comment]
> The `remote` location was missing in the `images.json` file.

Alright, thanks for catching this, I will add it to the scripts later.

**Comment by tischi** [comment]
> I think we should make sure that at least together with BDV-Playground, there is a peaceful co-existence. ;-)

Of course! In fact, what I would need right now is a (minimum) 2 weeks hackathon with Nico to fix all of this. But who pays me for this... Or, who would would do all the other stuff... It mainly is an issue of limited amount of resources for such developments at EMBL... Maybe that'll change, but not too soon. 

Anyway, I made good progress:

```
[ERROR] Module threw exception
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 160F3AB2D7241F06; S3 Extended Request ID: null), S3 Extended Request ID: null
```

using this address: `https://git.embl.de/pape/covid-em/-/raw/master/data`

**Comment by constantinpape** [comment]
> Given the load of dependencies that your plugins require, there is always the risk of something to misbehave.

Yes, we need to fix this, but there is only so much time ...
I think we should make a concerted effort to push all the relevant things upstream at some point.
But now we really have other priorities ...

**Comment by tischi** [comment]
works :-)

![image](https://user-images.githubusercontent.com/2157566/82065160-09cbc500-96ce-11ea-803b-117eb45d6d93.png)

```
AWSCredentialsProvider credentialsProvider = new DefaultAWSCredentialsProviderChain();
```

This found the credentials that I stored on my mac as I described somewhere else.

I will update `bigdataviewer-core` accordingly and release to my update-site.
Let you know once it is there.

**Comment by tischi** [comment]
ok. please try now.
with this address: `https://git.embl.de/pape/covid-em/-/raw/master/data`

**Comment by martinschorb** [comment]
Wohooo,  geilo!

Perfekter Einstieg ins Wochenende. Euch ein schönes dieses...!

**Comment by tischi** [comment]
@martinschorb 
Erklaerst Du das dann den Kollaboratoren?
Auch, dass sie am Besten ein eigenes Fiji dafuer haben, dass sie nicht mehr updaten, wenn Sie mal meine Update Site enabled haben?
😉

**Comment by constantinpape** [comment]
Done.
